name: Deploy to Firebase (Main)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Google Application Credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ${{ github.workspace }}/service-account.json

      - name: Deploy to Firebase
        run: firebase deploy --only hosting:mixtaperadio --project area-4b
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json